#!/usr/bin/python3

import sys
from PIL import Image, ImageDraw

def createImage(input_file, output_file):
    WIDTH, HEIGHT = 720, 480
    
    img = Image.new("RGB", (WIDTH, HEIGHT), (255, 255, 255))
    draw = ImageDraw.Draw(img)
    
    CAM_MAX_DIST = 2**16-1

    min_dist, max_dist = CAM_MAX_DIST, -CAM_MAX_DIST
    min_wanted, max_wanted = 0, 192
    
    with open(input_file, 'r') as f:
        for s in f.readlines():
            for d in map(lambda x : int(x), s.split()):
                min_dist, max_dist = min(min_dist, d), max(max_dist, d if d < CAM_MAX_DIST else 0)

    with open(input_file, 'r') as f:
        i, j = 0, 0
        for s in f.readlines():
            for d in map(lambda x : int(x), s.split()):
                d = int((d - min_dist) / (max_dist - min_dist) * (max_wanted - min_wanted)) if d <= max_dist else 255
                draw.point((j, i), fill = "#%02x%02x%02x" % (d, d, d))
                j += 1
            i, j = i + 1, 0
    
    img.save(output_file)

def main():
    if len(sys.argv) == 3:
        createImage(sys.argv[1], sys.argv[2])
    else:
        print("Invalid arguments. Try to use './visual [input=depth_image] [output]'")
        exit(1)

main()
